Squashed commit of the following:
commit c054099d497cc5f26694a0f6721ae4cd8cb1c696
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Tue Dec 7 10:26:22 2021 -0500

    Update setup.cfg to show python 3.9 support

commit d1ee3247a129ba5776b4ff3892696d6f4a5a9f8b
Merge: dbeccbc ce11661
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Tue Nov 30 12:42:32 2021 -0500

    Merge pull request #79 from philipstarkey/break-circular-dependency

    Updated BLACS to use the new labscript-utils device registry.

commit ce11661c3f3db59bb5f52978801fab1cc0db8c7e
Merge: 741d790 dbeccbc
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Tue Nov 30 12:39:25 2021 -0500

    Merge branch 'master' into break-circular-dependency

commit dbeccbcec3df9f384b0160a225748bdab7a3d227
Merge: 641cdeb 7f9552a
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Wed Nov 24 11:22:29 2021 -0500

    Merge pull request #87 from zakv/fix-86

    Fixed issue where blacs couldn't close with certain tabs

commit 641cdeb585c846d0a9675b29540f7a1c7b4f2622
Merge: e8bdd1b ff6f447
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Wed Nov 10 16:57:14 2021 -0500

    Merge pull request #81 from zakv/conversion-import-error

    Fix Bug in AO.__init__() When Unit Conversion Import Fails

commit e8bdd1bcc3d58fc52ebbb8eea477a79191a49bcf
Merge: b083bb8 868b991
Author: David Meyer <dihm@users.noreply.github.com>
Date:   Fri Jul 16 16:06:03 2021 -0400

    Merge pull request #80 from dihm/blacs-docs

    Initial pass at BLACS docs

commit 868b99133bc67e8c5eebdd03fb97330e20941eac
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Thu Jul 15 10:37:40 2021 -0400

    Add docstring coverage check to build.

commit ce2c490bb5e960e0a7f470807913ac4250ca9476
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Thu Jul 15 10:37:15 2021 -0400

    Update sphinx pin.

commit a3e604061ea544f182eb57fdb3a0ead49abe3c4c
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Fri Jul 9 12:05:25 2021 -0400

    Add unlisted dependency in `compile_and_restart` on runmanager.

commit 2c0ec0c7a97fc37f2a150f003787557d2d45f635
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Fri Jul 9 11:57:36 2021 -0400

    Add missing import to conf.py

commit 03a53e27dab8ed40cba80ad2ef0ed4717113b174
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Fri Jul 9 11:55:06 2021 -0400

    Add API documentation for the BLACS GUI.

commit 869d28f4fc43ed0ae907360797df3f48af66deb2
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Fri Jul 9 11:52:38 2021 -0400

    Version bump sphinx to match rest of modules.

commit 06539c4708f7ae5ce9142f994d19fcd9b7c4c084
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Tue Nov 17 19:41:19 2020 -0500

    Updating high level docs from @philipstarkey Thesis.

commit d542c2f867f8251e732a7b1479b2446cd846f138
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Tue Nov 17 17:27:25 2020 -0500

    Add API documentation for the blacs submodules.

    Relies on recursive autosummary and a custom template.

    In testing builds, noticed that experiment_queue and plugins depended on
    a properly set up labconfig; namely experiment_shot_storage. Might be an
    issue on readthedocs.

commit 057d8498ae0d8616455c7851cc1900df3845b510
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Tue Nov 17 17:03:41 2020 -0500

    Add pyqt5 intersphinx inventory.

commit b083bb878048b2d98de90c2128d2f240f970f066
Merge: 2bd2aa6 3930ffc
Author: chrisjbillington <chrisjbillington@gmail.com>
Date:   Fri Apr 9 12:27:24 2021 +1000

    Merge branch 'dihm/setuptools_scm-fix'

commit 3930ffcb7e2deb17dea62936f1d2ba4c48442c8d
Author: chrisjbillington <chrisjbillington@gmail.com>
Date:   Fri Apr 9 12:26:48 2021 +1000

    * Continue to set local scheme based on env var
      in `__version__.py` for consistency.

    * Don't require specific setuptools or [toml] extra from setuptools_scm.
      We aren't configuring setuptools_scm in pyproject.toml anyway, and
      setuptools_scm itself will specify a fairly recent version of
      setuptools (we have no special requirement ourselves)

    * no longer use env var for version_scheme in setup.py, since we're now
      hard-coding release-branch-semver.

commit 75b10aa80ddf9d4bbc3c223a3ee1758b6b5810a8
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Fri Apr 2 13:50:25 2021 -0400

    Update setup.cfg

    Adds setuptools-scm with required version.

commit feff40466535d242d79f7324651daaa9bdeb709f
Author: David Meyer <dihm.meyer@gmail.com>
Date:   Tue Dec 29 14:22:20 2020 -0500

    Update default setuptools_scm version scheme to release-branch-semver.

    This fixes the circular dependency issue between blacs and labscript-devices.

commit 7f9552a6dcf13dc0d48265e34db7b655e9d753cc
Author: Zak V <zakven@mit.edu>
Date:   Fri Jan 15 08:23:51 2021 -0500

    Fixed issue where blacs couldn't close if a tab doesn't have shutdown_workers() and finalise_close_tab() methods.

    In particular, PluginTab doesn't have these methods.

commit 2bd2aa6c9dc20fa9674676619aec4d9d4d53848b
Merge: 0e153f2 ca203a4
Author: Chris Billington <chrisjbillington@gmail.com>
Date:   Tue Jan 5 13:55:02 2021 +1100

    Merge pull request #85 from zakv/fix-84

    Fix copy/paste bug where stop_order is set to start_order

commit ca203a42235141f2c2709f459fe7bf718eb6752b
Author: Zak V <zakven@mit.edu>
Date:   Mon Jan 4 21:16:06 2021 -0500

    Fixed copy/paste bug where stop_order was set to start_order in
    QueueManager.manage().

commit ff6f447440516521f5de2df2c677c01eee6cde40
Author: Zak V <zakven@mit.edu>
Date:   Tue Nov 24 17:30:12 2020 -0500

    Corrected mistaken change to AO.__init__() error message in previous commit.

commit e0a615a5b440f1e8c6facd622c04515f3c0cf1ab
Author: Zak V <zakven@mit.edu>
Date:   Tue Nov 24 16:54:22 2020 -0500

    Fixed bug in AO.__init__() where failure to import a unit conversion class wasn't reported correctly, causing "AttributeError: 'NoneType' object has no attribute 'base_unit'".

commit 741d790a5586e20a1a3ed81ab8b03f9ab6802295
Author: philipstarkey <philipstarkey@users.noreply.github.com>
Date:   Thu Jul 16 17:17:02 2020 +1000

    Updated BLACS to use the new labscript-utils device registry.

    Removes the circular dependency on labscript-devices.

    This update assumes we will publish a new labscript-utils beta (3.1.0b1) shortly (so will  fail to build on RTD until that is done)