Fixed bug in AO.__init__() where failure to import a unit conversion class wasn't reported correctly, causing "AttributeError: 'NoneType' object has no attribute 'base_unit'".